'reinit'
'set mproj off'
'ini -s'

'open dynamic.ctl'
'xygrid'
'R=sqrt(pow(xgrid-64.5,2)+pow(ygrid-64.5,2))'
'core=R<=4'
'outer=(R>4)&(R<=12)'

'set x 32 97'
'set y 32 97'

'c'
'set grads off'
'set gxout grfill'
'set xaxis -16.25 16.25'
'set yaxis -16.25 16.25'
'set xlint 8'
'set ylint 8'
'set ccolor 4'
'd maskout(outer,outer)'
'draw xlab [km]'
'draw ylab [km]'
'off'
'set ccolor 2'
'd maskout(core,core)'
'gxprint /data/W.eddie/GoAmazon_VVM_Figs/domain.png'
